spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeeJangHyeop/cloud-config-repository
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: ['*']
      base-path: /